CREATE DATABASE api_golang;
USE api_golang;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_tokens (
  id SERIAL PRIMARY KEY,
  token VARCHAR(255) NOT NULL,
  user_id INT NOT NULL
);
